//EDIT ANY OF THESE TEXT LINES TO YOUR DESIRED INFORMATION
//IF YOU WANT TO ADD MORE, SIMPLY ADD ANOTHER LINE BUT THE LAST LINE MUST *NOT* HAVE A COMMA
_intelFile = _this select 0;

_randomText = selectRandom 
[
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
	"CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
	"DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
	"EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE",
	"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
	"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
	"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
	"IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII",
	"JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ",
	"KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK",
	"LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL",
	"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"//LAST LINE CANNOT HAVE A COMMA
];

//EDIT ANY OF THESE IMAGE LINES BY ADDING IN YOUR OWN CUSTOM IMAGES
//IF YOU WANT TO ADD MORE, SIMPLY ADD ANOTHER LINE BUT THE LAST LINE MUST *NOT* HAVE A COMMA
//ALSO DOUBLE CHECK THE PATH TO THE IMAGE
_randomImage = selectRandom
[
	"a3\structures_f_epc\Items\Documents\Data\document_secret_01_co.paa",
	"images\doc_1.jpg",
	"images\doc_2.jpg",
	"images\doc_3.jpg",
	"images\doc_4.jpg"//LAST LINE CANNOT HAVE A COMMA
];



_intelFile setVariable ["RscAttributeDiaryRecord_texture",_randomImage, true]; 
[_intelFile,"RscAttributeDiaryRecord",["Top Secret Documents",_randomText,""]] call bis_fnc_setServerVariable; 
_intelFile setVariable ["recipients", west, true]; 
