//To Do: edit script to be more adaptable


Lightlist = ["Lamps_base_F","Land_LampStreet_small_F","Land_LampStreet_F","Land_LampDecor_F","Land_LampHalogen_F","Land_LampHarbour_F","Land_LampShabby_F"];

_lamps = nearestObjects [lights,Lightlist,200];
[lights,["bass_kick",800,1]] remoteExec ["say3D",0];
{_x setHit ["light_1_hitpoint",0.99]} forEach _lamps;
{_x setHit ["light_2_hitpoint",0.99]} forEach _lamps;
{_x setHit ["light_3_hitpoint",0.99]} forEach _lamps;
{_x setHit ["light_4_hitpoint",0.99]} forEach _lamps;
sleep 0.5;
_lamps1 = nearestObjects [lights_1,Lightlist,200];
[lights_1,["bass_kick",800,1]] remoteExec ["say3D",0];
{_x setHit ["light_1_hitpoint",0.99]} forEach _lamps1;
{_x setHit ["light_2_hitpoint",0.99]} forEach _lamps1;
{_x setHit ["light_3_hitpoint",0.99]} forEach _lamps1;
{_x setHit ["light_4_hitpoint",0.99]} forEach _lamps1;
sleep 0.75;
_lamps2 = nearestObjects [lights_2,Lightlist,200];
[lights_2,["bass_kick",800,1]] remoteExec ["say3D",0];
{_x setHit ["light_1_hitpoint",0.99]} forEach _lamps2;
{_x setHit ["light_2_hitpoint",0.99]} forEach _lamps2;
{_x setHit ["light_3_hitpoint",0.99]} forEach _lamps2;
{_x setHit ["light_4_hitpoint",0.99]} forEach _lamps2;
sleep 1.5;
_lamps3 = nearestObjects [lights_3,Lightlist,200];
[lights_3,["bass_kick",800,1]] remoteExec ["say3D",0];
{_x setHit ["light_1_hitpoint",0.99]} forEach _lamps3;
{_x setHit ["light_2_hitpoint",0.99]} forEach _lamps3;
{_x setHit ["light_3_hitpoint",0.99]} forEach _lamps3;
{_x setHit ["light_4_hitpoint",0.99]} forEach _lamps3;
sleep 0.40;
_lamps4 = nearestObjects [lights_4,Lightlist,200];
[lights_4,["bass_kick",800,1]] remoteExec ["say3D",0];
{_x setHit ["light_1_hitpoint",0.99]} forEach _lamps4;
{_x setHit ["light_2_hitpoint",0.99]} forEach _lamps4;
{_x setHit ["light_3_hitpoint",0.99]} forEach _lamps4;
{_x setHit ["light_4_hitpoint",0.99]} forEach _lamps4;
sleep 0.75;
_lamps5 = nearestObjects [lights_5,Lightlist,200];
[lights_5,["bass_kick",800,1]] remoteExec ["say3D",0];
{_x setHit ["light_1_hitpoint",0.99]} forEach _lamps5;
{_x setHit ["light_2_hitpoint",0.99]} forEach _lamps5;
{_x setHit ["light_3_hitpoint",0.99]} forEach _lamps5;
{_x setHit ["light_4_hitpoint",0.99]} forEach _lamps5;
sleep 0.75;
_lamps6 = nearestObjects [lights_6,Lightlist,150];
[lights_6,["bass_kick",800,1]] remoteExec ["say3D",0];
{_x setHit ["light_1_hitpoint",0.99]} forEach _lamps6;
{_x setHit ["light_2_hitpoint",0.99]} forEach _lamps6;
{_x setHit ["light_3_hitpoint",0.99]} forEach _lamps6;
{_x setHit ["light_4_hitpoint",0.99]} forEach _lamps6;
